RESULT = umbrales
SOURCES   = src/conexion_db.ml src/grafica.ml src/conf.ml src/solucion.ml src/svg.ml src/umbrales.ml 
DOC_FILES = src/conexion_db.ml src/grafica.ml src/solucion.ml src/svg.ml src/umbrales.ml
LIBS = sqlite3 str
INCDIRS = +sqlite3 +str
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
